pages/Feedback Form.md
=> Form Page Update

_newsroom/Tender Notices.md, _tender-details/Tender for Canberra CCC Trade Fair.md, _tender-details/collection.yml, pages/Latest Government Policies.md
remove woodlands CCC trade fair and added Canberra CCC trade fair
=> Removal and Add tender notice

_our-network/Partners/Project We Care.md
=> Project We Care page

_our-programmes/CC Courses/Be a Training Provider.md, pages/Resources for PA Trainers & Operators.md
We have added a word "end" before September 2023, for review and approval, please.
=> Review PA website page - Be a Training Provider 

_our-programmes/CC Courses/Be a Training Provider.md
Please refer to the email sent this morning.
=> Be a Training Provider 

_our-programmes/CC Courses/Be a Training Provider.md, _our-programmes/SPARKS@BukitCanberra/Volunteering Opportunities.md, _sparks-volunteer-programmes/Arts & Heritage/Art Dream Alive.md, _sparks-volunteer-programmes/Nurturing Our Children/PSLE Coaching Programme.md, _sparks-volunteer-programmes/Smart Nation/SparksMakers: Empowering Tomorrow’s Innovators.md
Added 2 new programmes
1)	Art-Dream Alive (Arts & Heritage)
2)	SparksMakers: Empowering Tomorrow’s Innovators (Smart Nation)
Amend the date in PSLE Coaching Programme (Nurturing our Children) Commitment.
=> Added 2 new programmes and amended 1 programme for Sparks@Bukit Canberra

_our-network/NACLI/Campus Facilities.md
=> Update of rental form

_our-network/Community Clubs/CC Information.md, _our-network/PA's Network.md, _our-network/Partners/PA Partners.md, _our-network/Partners/WeCare PALs.md, _sparks-volunteer-programmes/Arts & Heritage/Art Dream Alive.md, _sparks-volunteer-programmes/Caring for Our Community/Senior Befriending Programme.md, _sparks-volunteer-programmes/Nurturing Our Children/Homework Café.md, _sparks-volunteer-programmes/Nurturing Our Children/kidsREAD.md
I have made the following amendment at the web portal.
Under Arts & Heritage
Art Dream Alive – Change the day to Every Friday
Under Caring for Our Community
Senior Befriending Programme – Change the day to Every Tuesday
Under Nurturing Our Children
Homework Café – Change the day to Every Wednesday and change the timing to 7pm to 9pm
kidsRead – Change the timing to 2.30pm to 3.30pm
=> Amendment to 4 programmes (Day & Timing)

_about-us/Contact Us.md
Added links to PA FB, IG, TikTok, Linkedin and WhatsApp Channel
=> Added PA socials to Contact Us page

_about-us/Contact Us.md
updated broken link to https://whatsapp.com/channel/0029Va7A5KkCXC3Bf6RIdS01
=> Fixed broken WA channel link

_our-network/NACLI/Learn with NACLI.md
=> Uploaded updated pdf file

_engage/Be Our Volunteer.md, _our-volunteers/Volunteering Opportunities.md
Change of website address for the public to sign up as a volunteer with PA.
=> Change of website from Grassroots Connect to GRL@PA

_tender-details/Tender for Chinatown Mid Autumn Fairs 2024.md
(1)	To request for the tender documents, please email to Lee_Xiaohui@pa.gov.sg, Celeste_Sim@pa.gov.sg and Chng_Pei_Joo@pa.gov.sg. 
For more information, please contact Lee Xiaohui,  Celeste Sim or Chng Pei Joo at 6272 3878  or email at Lee_Xiaohui@pa.gov.sg / Celeste_Sim@pa.gov.sg/ Chng_Pei_Joo@pa.gov.sg.
=> update of PIC under Details section in tender notice - added Chng_Pei_Joo@pa.gov.sg 

index.md
Edited updated "108 Community Clubs" to "112 Community Clubs"
=> Updated Find My CC section

_our-network/Our Tampines Hub/Our Tampines Hub.md
SportsSG team has requested for OTH user to update the url of "sports facilities" URL to: https://activesg.gov.sg/activities/list
Paragraph:
Residents can enjoy a range of amenities such as sports facilities, regional library, hawker centre, retail shops and the community club.
=> Update of "sports facilities" URL to: https://activesg.gov.sg/activities/list

_cc-details/Sembawang Community Club.md
Sembawang CC closed for reno. Added temp office address and changed phone number
=> Changed Sembawang CC's address

_tender-details/Tender for Street Light Up Decorative Items for Chinatown Chinese New Year 2025.md
=> Update Newsroom Tender Notice Page

index.md
Changed message from scam awareness to informing that PA hotline is down
=> Edit Homepage notification banner

index.md
=> Removed Phone Line Down notice

_newsroom/Tender Notices.md, _our-network/Member Organisations.md, _tender-details/Tender for Provision of Auxiliary Police Services for Chinatown Chinese New Year Celebrations 2025.md, _tender-details/Tender for Provision of Refuse Collection & Cleaning Services for Chinatown Chinese New Year 2025.md, _tender-details/Tender for Street Light Up Decorative Items for Chinatown Chinese New Year 2025.md, _tender-details/collection.yml
Removed broken links from Partners Page https://stu.org.sg/ , http://www.spc.org.sg/ , and http://www.sriwana.com/
=> Removed broken links

news-and-speeches/speeches/_posts/2024-09-29-post-Speech by PA's Deputy Chairman Edwin Tong, at the People’s Association Community Seminar 2024.md
Removed the word "our" from the sentence: "expanding our community participation across segments of society."
=> edit to DC's speech

news-and-speeches/speeches/_posts/2024-09-29-post-Speech by PA's Deputy Chairman Edwin Tong, at the People’s Association Community Seminar 2024.md
added missing comma to DC's speech
=> added a missing comma

news-and-speeches/news/_posts/2024-10-22-post-PA Statement on Incident at Trivelis Estate in Clementi.md
change Grassroots Advisor to Grassroots Adviser (with e)
=> Changed spelling of Adviser (with e) for News Release

pages/Deepavali.md
Created Deepavali page on behalf of News Hub.
Write up has been endorsed by NARPANI
=> Deepavali Page

_tender-details/Tender for Replacement of Existing Fire Alarm & Mimic Panels at Sengkang Community Hub Building.md
=> Tender updates

index.md, pages/ONE COUNTDOWN 2025: Heartland Locations.md
Changed copy of the following events to add in the CO:
Hougang – Igniting Sparks of Hope
Bedok – Illuminate 2025
Marsiling – MY Countdown
=> Updated copy and added One Countdown to homepage

pages/ONE COUNTDOWN 2025: Heartland Locations.md
Organised by about 1,700 grassroots leaders and community volunteers – from dedicated students, working professionals, to seasoned seniors – who are eager to make a difference in their communities, the 17 heartland countdown celebrations promise to offer vibrant and inclusive programmes that bring joy and celebration to people of all ages. These events bring the spirit of unity, volunteerism, and community engagement.
=> added paragraph as per Mei Ling's advice

_our-programmes/Community Sports/Latest Happenings.md
Request to post a YouTube shorts video of Community Sports Appreciation 2024 on Community. Kindly note this video is originally from DC's Instagram Story posted on 20 Oct 2024 (1 day after the actual event on 19 Oct 2024). 
Review deadline: 20 Dec 2024
=> Highlights of Community Sports Appreciation 2024

news-and-speeches/news/_posts/2024-12-04-post-PA to organise 17 heartland countdowns for residents to welcome 2025 as One Community.md
added "More information on the heartland celebrations can be found in the Annex."
=> added in a one liner to refer to the annex on countdown MR

_ramadan-and-hari-raya/Ramadan and Hari Raya Events.md
made some minor spelling changes
=> minor edits to hari raya events page

_our-programmes/Community Sports/Community Championship.md
Corrected URL to OnePA website
Updated registration links for upcoming competitions
=> Updating Community Championship Webpage

_our-network/PAssion Wave.md
Hi Hafiz, I have made some amendments by updating one picture and inserting the individual hyerlinks for 6 outlets.
=> Update of picture and hyperlink for PAssion Wave

_newsroom/Tender Notices.md, _our-network/Partners/PA Partners.md, _our-programmes/PA Cares @ President's Challenge.md, _tender-details/Invitation to Tender to Build, Manage, Maintain and Operate All Weather Covered Tent Futsal Courts.md, _tender-details/collection.yml
=> Community Championship

_our-programmes/PA Cares @ President's Challenge.md
Did a minor edit to the main body texts of the webpage
=> Updating PA Cares @ President's Challenge Webpage
